### PR TITLE
Add a section about service bindings

### PR DESCRIPTION
**Pull request by loewenstein**

### CODE REVIEW

**Comment by loewenstein** [comment]
Let's wait with this change until we might have a better answer for e.g. packit buildpacks.

**Comment by loewenstein** [comment]
@modulo11 I added the `packit` pull request. WDYT, should we add it like this to the RFC?

**Comment by c0d1ngm0nk3y** [comment]
What is the value gain in putting this into the RFC? There is noting to do on `cf` side, right?

**Comment by loewenstein** [comment]
Hi @c0d1ngm0nk3y,

it was specifically requested to be added in https://github.com/cloudfoundry/community/pull/796#discussion_r1543065323, the other RFC had [a section about it](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0017-add-cnbs.md#service-bindings) as well and an alternative to adding it to Paketo buildpacks is https://github.com/cloudfoundry/community/pull/804 which would be work in CF for the benefit of being independent from a concrete implementation of CNBs.

Does it make more sense?

**Comment by c0d1ngm0nk3y** [comment]
I am just wondering if `libpak` and `libcnb` is too much details. But if the previous rfc already addressed this, this is already aligned. Isn't it? :)

**Comment by loewenstein** [comment]
The existing RFC ends with
> ### Recommendation
> Updating the Paketo buildpacks to consume Cloud Foundry environment variables appears to be the easier option. However, given that there are at least two viable options for buildpack service binding consumption, this RFC proposes making the final decision at implementation time.

**Comment by c0d1ngm0nk3y** [comment]
> this RFC proposes making the final decision at implementation time.

I like that actually.

**Comment by loewenstein** [comment]
> > this RFC proposes making the final decision at implementation time.
> 
> I like that actually.

Isn't that very similar to what I propose here? I.e. 
> When #804 gets approved and implemented (with option 2), this requirement will be removed.

Anyway, I am open for re-phrasing proposals, but I think we should include something about service bindings.

**Comment by c0d1ngm0nk3y** [comment]
> this requirement will be removed.

I am just a bit confused. This is a requirement towards buildpacks and not `cf`, right? So I wonder what the benefit in mentioning this is. Especially since the predecessor pr already saw this as implementation detail.

But sgtm, I am just a little concerned that we put little by little to much into this RFC.

**Pull request closed without merging**
